### ISSUE TITLE
config.yml  注意个人隐私信息

### ISSUE THREAD

**Issue by sof-Flandre** [DongZhouGu/SHU-selfreport-mail#1]

**Comment by DongZhouGu** [comment]
感谢您的提醒，发件邮箱为个人不使用的公共邮箱，仅为方便通知用。
本次更新包括：
1. 隐去了邮件中的一些可能造成隐私困扰的内容；
2. 可以在secret中将邮箱设置为null，将不再收到邮件提醒
您可以根据[readme](https://github.com/DongZhouGu/SHU-selfreport-mail#readme)中的内容更新仓库确保使用最新的版本。
